package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviMapCityInfo;
import com.autonavi.tsp.workbackend.model.NaviMapCityInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviMapCityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int countByExample(NaviMapCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int deleteByExample(NaviMapCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int insert(NaviMapCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int insertSelective(NaviMapCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    List<NaviMapCityInfo> selectByExample(NaviMapCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    NaviMapCityInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviMapCityInfo record, @Param("example") NaviMapCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByExample(@Param("record") NaviMapCityInfo record, @Param("example") NaviMapCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByPrimaryKeySelective(NaviMapCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_map_city_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByPrimaryKey(NaviMapCityInfo record);
}