package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviApkVersion;
import com.autonavi.tsp.workbackend.model.NaviApkVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviApkVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int countByExample(NaviApkVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int deleteByExample(NaviApkVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int insert(NaviApkVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int insertSelective(NaviApkVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    List<NaviApkVersion> selectByExample(NaviApkVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    NaviApkVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviApkVersion record, @Param("example") NaviApkVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByExample(@Param("record") NaviApkVersion record, @Param("example") NaviApkVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByPrimaryKeySelective(NaviApkVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_apkversion
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByPrimaryKey(NaviApkVersion record);
}