package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviResourcePublish;
import com.autonavi.tsp.workbackend.model.NaviResourcePublishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviResourcePublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int countByExample(NaviResourcePublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int deleteByExample(NaviResourcePublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int insert(NaviResourcePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int insertSelective(NaviResourcePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    List<NaviResourcePublish> selectByExample(NaviResourcePublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    NaviResourcePublish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviResourcePublish record, @Param("example") NaviResourcePublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByExample(@Param("record") NaviResourcePublish record, @Param("example") NaviResourcePublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByPrimaryKeySelective(NaviResourcePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_publish
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByPrimaryKey(NaviResourcePublish record);
}