package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviResourceVersion;
import com.autonavi.tsp.workbackend.model.NaviResourceVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviResourceVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int countByExample(NaviResourceVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int deleteByExample(NaviResourceVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int insert(NaviResourceVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int insertSelective(NaviResourceVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    List<NaviResourceVersion> selectByExample(NaviResourceVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    NaviResourceVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviResourceVersion record, @Param("example") NaviResourceVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByExample(@Param("record") NaviResourceVersion record, @Param("example") NaviResourceVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByPrimaryKeySelective(NaviResourceVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_resource_version
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByPrimaryKey(NaviResourceVersion record);
}