package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviSystem;
import com.autonavi.tsp.workbackend.model.NaviSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int countByExample(NaviSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int deleteByExample(NaviSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int deleteByPrimaryKey(String syscode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int insert(NaviSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int insertSelective(NaviSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    List<NaviSystem> selectByExample(NaviSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    NaviSystem selectByPrimaryKey(String syscode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviSystem record, @Param("example") NaviSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByExample(@Param("record") NaviSystem record, @Param("example") NaviSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByPrimaryKeySelective(NaviSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_sys
     *
     * @mbggenerated Tue Jul 14 17:28:14 CST 2015
     */
    int updateByPrimaryKey(NaviSystem record);
}