package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviCityVersionCompat;
import com.autonavi.tsp.workbackend.model.NaviCityVersionCompatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviCityVersionCompatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int countByExample(NaviCityVersionCompatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int deleteByExample(NaviCityVersionCompatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int insert(NaviCityVersionCompat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int insertSelective(NaviCityVersionCompat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    List<NaviCityVersionCompat> selectByExample(NaviCityVersionCompatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    NaviCityVersionCompat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviCityVersionCompat record, @Param("example") NaviCityVersionCompatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int updateByExample(@Param("record") NaviCityVersionCompat record, @Param("example") NaviCityVersionCompatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int updateByPrimaryKeySelective(NaviCityVersionCompat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_city_version_compat
     *
     * @mbggenerated Fri Jul 17 11:47:55 CST 2015
     */
    int updateByPrimaryKey(NaviCityVersionCompat record);
}