package com.autonavi.tsp.workbackend.dao;

import com.autonavi.tsp.workbackend.model.NaviBaseResInfo;
import com.autonavi.tsp.workbackend.model.NaviBaseResInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NaviBaseResInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int countByExample(NaviBaseResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int deleteByExample(NaviBaseResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int insert(NaviBaseResInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int insertSelective(NaviBaseResInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    List<NaviBaseResInfo> selectByExample(NaviBaseResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    NaviBaseResInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") NaviBaseResInfo record, @Param("example") NaviBaseResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByExample(@Param("record") NaviBaseResInfo record, @Param("example") NaviBaseResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByPrimaryKeySelective(NaviBaseResInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navi_base_res_info
     *
     * @mbggenerated Mon Jul 20 15:45:38 CST 2015
     */
    int updateByPrimaryKey(NaviBaseResInfo record);
}