package com.autonavi.tsp.workbackend.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.autonavi.tsp.workbackend.model.RomMatchCar;
import com.autonavi.tsp.workbackend.model.RomMatchCarExample;
import com.autonavi.tsp.workbackend.model.RomMatchCarName;

public interface RomMatchCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int countByExample(RomMatchCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int deleteByExample(RomMatchCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int insert(RomMatchCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int insertSelective(RomMatchCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    List<RomMatchCar> selectByExample(RomMatchCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    RomMatchCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") RomMatchCar record, @Param("example") RomMatchCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int updateByExample(@Param("record") RomMatchCar record, @Param("example") RomMatchCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int updateByPrimaryKeySelective(RomMatchCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_match_car
     *
     * @mbggenerated Tue Feb 03 13:49:10 CST 2015
     */
    int updateByPrimaryKey(RomMatchCar record);

    /**
     * 查询该ROM适用的车型
     * @param romVersionId
     * @return
     */
    List<RomMatchCarName> selectByRomPushId(String romVersionId);

    /**
     * 批量插入
     * @param records
     */
    void insertBatch(List<RomMatchCar> records);
}