package com.autonavi.tsp.workbackend.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.autonavi.tsp.workbackend.model.RomPush;
import com.autonavi.tsp.workbackend.model.RomPushExample;

public interface RomPushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int countByExample(RomPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int deleteByExample(RomPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int insert(RomPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int insertSelective(RomPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    List<RomPush> selectByExample(RomPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    RomPush selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") RomPush record, @Param("example") RomPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int updateByExample(@Param("record") RomPush record, @Param("example") RomPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int updateByPrimaryKeySelective(RomPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_push
     *
     * @mbggenerated Thu Jan 15 18:52:33 CST 2015
     */
    int updateByPrimaryKey(RomPush record);

    /**
     * 分页查询
     * @param param
     * @return
     */
    List<RomPush> findByPage(Map param);
}