package com.autonavi.tsp.workbackend.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.autonavi.tsp.workbackend.model.RomVersion;
import com.autonavi.tsp.workbackend.model.RomVersionExample;

public interface RomVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int countByExample(RomVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int deleteByExample(RomVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int insert(RomVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int insertSelective(RomVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    List<RomVersion> selectByExample(RomVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    RomVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") RomVersion record, @Param("example") RomVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int updateByExample(@Param("record") RomVersion record, @Param("example") RomVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int updateByPrimaryKeySelective(RomVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rom_version
     *
     * @mbggenerated Thu Jan 08 13:07:03 CST 2015
     */
    int updateByPrimaryKey(RomVersion record);

    /**
     * 分页查询
     * @param param
     * @return
     */
    List<RomVersion> findByPage(Map param);

    /**
     * 查询比指定ROM版本低的所有ROM版本记录
     * @param id
     * @return
     */
    List<RomVersion> queryLowRomVersion(String id);

    /**
     * 获取ROM下一个更新版本信息
     * @param name
     * @param version
     * @return
     */
    RomVersion getNextUpgradeRomVersion(@Param("name") String name, @Param("version") String version);
}