package com.autonavi.tsp.workbackend.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.autonavi.tsp.workbackend.model.VehicleBrand;
import com.autonavi.tsp.workbackend.model.VehicleBrandExample;

public interface VehicleBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int countByExample(VehicleBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int deleteByExample(VehicleBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int insert(VehicleBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int insertSelective(VehicleBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    List<VehicleBrand> selectByExample(VehicleBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    VehicleBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") VehicleBrand record, @Param("example") VehicleBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByExample(@Param("record") VehicleBrand record, @Param("example") VehicleBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByPrimaryKeySelective(VehicleBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_brand
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByPrimaryKey(VehicleBrand record);
}