package com.autonavi.tsp.workbackend.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.autonavi.tsp.workbackend.model.VehicleVersion;
import com.autonavi.tsp.workbackend.model.VehicleVersionExample;

public interface VehicleVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int countByExample(VehicleVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int deleteByExample(VehicleVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int insert(VehicleVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int insertSelective(VehicleVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    List<VehicleVersion> selectByExample(VehicleVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    VehicleVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") VehicleVersion record, @Param("example") VehicleVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByExample(@Param("record") VehicleVersion record, @Param("example") VehicleVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByPrimaryKeySelective(VehicleVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_version
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByPrimaryKey(VehicleVersion record);
}