package com.autonavi.tsp.workbackend.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.autonavi.tsp.workbackend.model.VehicleYear;
import com.autonavi.tsp.workbackend.model.VehicleYearExample;

public interface VehicleYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int countByExample(VehicleYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int deleteByExample(VehicleYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int insert(VehicleYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int insertSelective(VehicleYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    List<VehicleYear> selectByExample(VehicleYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    VehicleYear selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") VehicleYear record, @Param("example") VehicleYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByExample(@Param("record") VehicleYear record, @Param("example") VehicleYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByPrimaryKeySelective(VehicleYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_year
     *
     * @mbggenerated Fri Jan 16 17:45:20 CST 2015
     */
    int updateByPrimaryKey(VehicleYear record);
}